# Generated by Django 4.2.4 on 2023-09-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="longtitude", new_name="longitude",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Vendor"), (2, "Customer")], null=True
            ),
        ),
    ]
